import React from "react";

class LorenIpsum extends React.Component {
    constructor(props) {
        super(props);
    }

    getIpsumText(ipsumLength) {
        let text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada a mauris non scelerisque. Nam pretium felis eget sagittis tincidunt. Aenean mattis fringilla orci. Ut eget dui sem. In non convallis sapien, id consectetur ante. Suspendisse malesuada at metus eget iaculis. Cras purus lorem, laoreet vitae lorem vitae, porttitor malesuada risus. Aenean id sodales risus, nec condimentum justo. Vestibulum ac hendrerit eros, ac volutpat nibh. Curabitur ac venenatis massa. Pellentesque cursus neque quis elit finibus, vel ultricies est facilisis. " +
        "Sed pretium lorem sit amet est fringilla aliquam quis eu justo. Integer tincidunt ac lectus quis semper. Suspendisse cursus ac enim in convallis. Nulla aliquam consequat diam, vel tristique ipsum feugiat quis. Nulla efficitur eget lacus id condimentum. Vestibulum eget blandit enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin sem massa, volutpat et faucibus eget, sollicitudin eget tortor. " +
        "Suspendisse volutpat scelerisque arcu. Vivamus ut ligula vel turpis sodales mollis nec sit amet odio. Etiam sollicitudin molestie ante, eget viverra neque iaculis et. Etiam finibus, magna nec aliquet cursus, mauris nulla placerat dolor, a posuere elit sapien sed nisi. Aenean in tempus dolor. Vivamus vel orci ligula. Nullam sagittis accumsan nunc maximus bibendum. Suspendisse ut pretium velit. Vestibulum volutpat mi felis, a viverra nulla tristique at. Fusce non mattis erat. Etiam interdum erat nec tortor venenatis condimentum. Curabitur elementum tellus sit amet accumsan ultrices. In vitae augue elementum, ultricies augue vitae, vestibulum nisi. Morbi ut sem dignissim sem ullamcorper vulputate eget eget ligula. Proin sagittis nunc vitae egestas volutpat. Donec tempus nunc dolor, eu tristique libero tincidunt ut. " +
        "Nulla eu lobortis diam, sed luctus est. Donec viverra eget nisl consectetur venenatis. Donec bibendum sem et urna mattis, vitae tristique augue iaculis. Aliquam vulputate, elit in tempor ullamcorper, tellus leo dictum lorem, in euismod diam purus sit amet velit. Quisque sed arcu nec enim pretium ultricies eget ac elit. Fusce risus dolor, porta a nulla vitae, interdum facilisis mauris. Suspendisse feugiat sem eget lorem luctus tristique. Sed euismod quam augue, a congue tellus cursus ac. Vestibulum augue tortor, consectetur non tristique at, molestie at quam. Ut sodales mattis volutpat. Nam sit amet rutrum purus, id eleifend massa. In metus mauris, bibendum ac dignissim ac, accumsan non orci. Phasellus aliquam facilisis metus nec fringilla. Quisque pellentesque eros pretium dapibus dapibus. Pellentesque id odio in ante commodo tincidunt. " +
        "In ac malesuada justo. Nullam dignissim posuere euismod. Nunc eget mauris dui. Sed pharetra id diam in eleifend. Phasellus orci magna, feugiat eget velit sit amet, lobortis mattis sem. Etiam pretium odio sed felis molestie pulvinar. Vivamus tempus arcu in dolor convallis, id eleifend sem placerat. Maecenas vel facilisis erat. Proin gravida dolor sed diam vestibulum commodo. Sed consequat, erat nec tempor rhoncus, mauris est molestie nibh, volutpat euismod arcu augue at est. Cras eget tristique risus. Pellentesque eleifend lectus magna, sit amet lobortis eros viverra eu. Suspendisse a dolor imperdiet, ultricies orci in, aliquet nulla. " +
        "Duis sapien quam, sodales eleifend est ac, rutrum fermentum sem. Pellentesque luctus, nibh sit amet luctus sollicitudin, diam dui tempor dolor, nec luctus nisi sapien rhoncus turpis. Mauris a massa vitae ex dapibus fringilla nec vel ipsum. Nulla erat ante, accumsan ut urna at, iaculis convallis sem. Cras ullamcorper quam sed condimentum accumsan. Donec id sapien sodales, iaculis felis at, congue purus. Praesent lorem ex, lacinia eget fermentum ut, laoreet id turpis. " +
        "Donec a tempus justo. In leo turpis, blandit ac elit sed, iaculis rhoncus ligula. Aliquam vel dui vitae velit sollicitudin aliquam. Pellentesque egestas suscipit diam, sed vulputate purus pulvinar id. Maecenas quis velit mi. Fusce neque ligula, faucibus nec venenatis nec, ullamcorper finibus eros. Aliquam lacinia, elit sed vulputate hendrerit, odio magna congue ipsum, in maximus libero nisi non elit. Nam ultrices ex ut metus varius efficitur. Nullam ornare nunc non maximus egestas. Aliquam ullamcorper sit amet diam vitae elementum. Praesent posuere aliquet varius. Aliquam pulvinar, sapien sit amet venenatis fringilla, est diam hendrerit quam, at efficitur sapien lacus at nisi. Integer dapibus arcu eget consectetur pharetra. Aliquam pulvinar id nunc in euismod. Aenean ut efficitur augue, id tincidunt nunc. Donec quis velit at est rutrum vehicula et sit amet arcu. " +
        "Mauris accumsan ultricies sapien, a sollicitudin tellus vulputate in. Proin at tellus eu orci gravida luctus nec non nulla. Sed condimentum odio maximus tortor ullamcorper, a finibus urna volutpat. Curabitur tellus justo, auctor ut libero malesuada, ultrices blandit velit. Suspendisse non velit et nisl dignissim euismod eu ut eros. Integer in laoreet metus. Aenean posuere, ipsum eu dictum varius, urna risus pellentesque nulla, sit amet sagittis nisi erat semper sem. Nulla fringilla euismod elit, nec malesuada odio luctus sed. Quisque non fermentum enim. Fusce sed turpis purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas eleifend at ante ac volutpat. Etiam ac nibh in diam facilisis vulputate nec dapibus sapien. Donec auctor leo a velit maximus eleifend. " +
        "Donec non pulvinar turpis. Etiam consequat ante mauris, nec malesuada sem venenatis tristique. Cras condimentum sit amet diam sit amet gravida. Proin sit amet commodo diam, ut suscipit urna. Cras id faucibus risus, et dapibus purus. Quisque vel est eget nibh consectetur vestibulum. In blandit rhoncus tortor, in imperdiet lorem condimentum id. Donec mollis odio eget luctus facilisis. Aenean ultricies mollis lorem, ut maximus enim. Proin id ante at nibh aliquam volutpat quis nec nibh. Ut ornare, turpis in efficitur blandit, ex mauris sollicitudin ligula, nec mollis nibh risus ut leo. Fusce sit amet venenatis elit, ut tincidunt sapien. In faucibus malesuada dictum. Donec venenatis arcu et nulla viverra sodales. Vestibulum urna massa, euismod vel odio ut, vestibulum porttitor nisi. Suspendisse quam odio, euismod non dolor id, pulvinar luctus felis. " +
        "Morbi tristique sem vitae diam semper fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed dictum eget sem nec rutrum. Nullam fermentum diam eu neque gravida, nec pharetra lectus mattis. Integer eleifend ac nisl id maximus. In commodo nisl non metus accumsan porttitor. Sed in tempus libero, non maximus libero. Praesent libero nulla, blandit vitae diam eget, euismod mollis augue. " +
        "Fusce sit amet pretium diam. Praesent sed nulla fringilla, hendrerit lectus eu, rutrum lectus. Vivamus maximus mauris a metus ullamcorper, ut elementum nunc accumsan. Nunc dictum nec nunc sit amet egestas. Pellentesque lorem odio, fringilla a mi a, aliquam feugiat eros. Nam ut lacus sit amet libero volutpat vulputate. Morbi eget orci ac tellus ullamcorper interdum sit amet vel lorem. " +
        "Nullam vehicula diam quis mauris fermentum, id condimentum libero placerat. Praesent id sem facilisis, ultrices ex sed, vulputate orci. Suspendisse potenti. Ut pellentesque mauris ac euismod volutpat. Ut maximus nibh condimentum ligula porttitor semper. Suspendisse sed dui eleifend, molestie justo ut, pellentesque risus. Vivamus fringilla enim vel blandit congue. Cras vel dictum ipsum, at ornare eros. Nulla sed placerat est. Duis et nunc ut odio condimentum pulvinar. Mauris rutrum a magna vel aliquet. Aliquam fringilla porta dolor nec vulputate. Proin condimentum sem ut ipsum sagittis consequat. In hac habitasse platea dictumst. Maecenas nec tempor orci. Vivamus mollis tortor id ultricies suscipit. " +
        "Proin sodales et augue quis aliquet. Nunc ut metus quis nibh hendrerit posuere. Nullam pharetra justo ac lorem sodales luctus. Duis dapibus, lectus et elementum tristique, arcu urna rhoncus lectus, sed laoreet nulla nisi condimentum orci. Nullam mollis felis ex, et congue ex gravida at. Sed viverra, neque vitae rutrum laoreet, mi leo elementum lorem, venenatis facilisis enim nisi at ipsum. Nam quis commodo nisi. Maecenas cursus molestie ligula non volutpat. Maecenas id mauris metus. Nam pretium placerat velit. Proin auctor tempus condimentum. Duis auctor diam quis tortor porttitor lobortis. Sed ut pulvinar urna. Pellentesque vestibulum, arcu et porttitor tincidunt, sapien mi porta justo, vel viverra dui ante vel leo. " +
        "Duis condimentum elit eu scelerisque vehicula. Aliquam viverra, leo at efficitur varius, arcu leo commodo felis, a condimentum enim dolor vel lacus. Cras faucibus ligula vel neque vulputate, sit amet porta odio facilisis. Aenean rutrum ac neque non imperdiet. Aliquam in mi quis odio ultrices feugiat ut non neque. Proin quis scelerisque massa. Integer porta mattis elit sit amet placerat. Proin turpis diam, luctus at sapien eu, porttitor vestibulum diam. Integer blandit feugiat congue. Vestibulum lacinia viverra congue. " +
        "Aliquam at ligula faucibus, aliquam ex at, bibendum leo. Sed vehicula diam velit, et ultricies elit facilisis eget. Sed eget elit tellus. Integer tincidunt ac nisl a maximus. Morbi in mattis risus. Integer eget ipsum et quam dignissim aliquet eget eu enim. Nulla id magna sit amet neque hendrerit dapibus a id ex. Vestibulum blandit sed nibh et fringilla. In sed molestie urna, id luctus metus. Nulla interdum non turpis a fringilla. Duis vitae leo et velit efficitur maximus sed quis sapien. Donec dignissim interdum ipsum, non porta enim luctus fringilla. Suspendisse cursus, ante eu fringilla molestie, mi risus vestibulum libero, eu varius sem eros ac leo. Nunc vehicula dictum nunc. Maecenas condimentum diam velit, ac dictum ex ornare sit amet. Integer in nisi commodo, sollicitudin ex in, dignissim enim. " +
        "Pellentesque a dui ut velit molestie facilisis. Morbi sit amet vehicula urna. Sed aliquet erat tellus, quis porttitor velit finibus id. Nunc vitae luctus nibh. Duis libero nibh, luctus id leo non, rhoncus feugiat dolor. Aliquam sodales metus nisi, non tincidunt risus sollicitudin vitae. Mauris eu faucibus orci, et pretium purus. Donec at sagittis velit. Quisque dapibus leo tellus, a condimentum dolor molestie sit amet. Ut sed egestas sapien. Vestibulum tristique, velit commodo varius dapibus, eros nunc viverra ligula, non euismod tortor eros maximus justo. Integer a sem nec magna feugiat eleifend. Nulla malesuada vulputate pretium. Quisque nec velit nisl. " +
        "Etiam venenatis placerat neque. Aenean blandit convallis diam at posuere. Donec bibendum mi mattis justo porta ultrices. Sed tempus odio a est euismod sagittis. Donec rhoncus, lacus at rhoncus maximus, mi odio aliquet libero, in cursus lacus lacus in magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer vitae velit pretium, ullamcorper sapien id, gravida neque. Duis a rutrum neque. " +
        "Aenean non iaculis velit, eget fringilla neque. Vestibulum elementum porttitor cursus. Nunc ut massa libero. Duis accumsan metus eu dignissim euismod. Aenean posuere aliquam odio a sagittis. Donec in tortor euismod, vestibulum leo a, elementum quam. Pellentesque interdum imperdiet nibh. Sed ornare eros non tristique ullamcorper. Vestibulum vulputate, elit eget ullamcorper sollicitudin, turpis turpis consectetur massa, eu viverra ipsum augue eu massa. " +
        "Aenean neque mi, vulputate elementum velit a, auctor ultrices tellus. Nam efficitur ornare blandit. Curabitur eget auctor quam. Praesent a diam dui. Aenean at risus ac felis eleifend commodo. Vestibulum urna odio, viverra sed efficitur interdum, eleifend a ligula. Phasellus mollis felis eu nibh tristique vulputate. Praesent mattis quam sed est consectetur, sed feugiat tortor ullamcorper. Sed placerat finibus magna. Nam scelerisque laoreet sollicitudin. " +
        "Donec sit amet quam at erat bibendum molestie. Aliquam vitae dui purus. Nulla ultrices id tellus ut faucibus. Nam pellentesque hendrerit nisl non euismod. Maecenas sit amet tincidunt ex, at sagittis massa. Vivamus nunc justo, mattis nec magna eget, dignissim consectetur turpis. In id sem sed massa tristique rhoncus. Maecenas rutrum tincidunt dapibus. In in purus sed mi tristique ultrices in ut nibh. Sed auctor mauris eu purus fermentum, ullamcorper tincidunt mauris vulputate. Etiam congue a arcu eu sollicitudin. Nam gravida sagittis orci, sed eleifend erat molestie non. Sed condimentum volutpat sapien, fringilla rhoncus orci dictum et. Nulla vehicula et nisi id imperdiet. " +
        "Curabitur maximus ex nec tristique consequat. Integer vulputate, justo vitae ullamcorper volutpat, dolor augue fringilla velit, eget porta nunc dui vel leo. Nam massa nulla, posuere eu turpis consectetur, convallis tincidunt tellus. Quisque aliquam suscipit nunc, at interdum nisl venenatis a. Praesent dictum semper porttitor. Vestibulum suscipit pharetra risus, eget ornare risus pulvinar eget. Curabitur pharetra pellentesque laoreet. Integer tincidunt purus ac mauris efficitur fermentum. Sed ac commodo sapien, condimentum luctus est. Maecenas elementum dui sit amet sem iaculis tincidunt. " +
        "Proin gravida, ligula eu mollis tempus, ipsum nunc pulvinar sem, ac varius lacus felis at lacus. Nulla sollicitudin imperdiet erat, eu rutrum erat sollicitudin et. Nullam eu risus augue. Vestibulum nec nisi dui. Duis vel turpis risus. Sed ac velit lacus. Suspendisse euismod pharetra iaculis. Ut non porta libero. Aliquam a massa in nisl gravida feugiat condimentum vel nunc. Vivamus purus nibh, porta eget magna vitae, mattis venenatis libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas eget imperdiet dui. Phasellus sollicitudin gravida nulla, iaculis sollicitudin lorem interdum quis. Fusce euismod purus eget odio ultricies dapibus. " +
        "Etiam pharetra ante arcu, et aliquet sem tincidunt in. Sed a dui eu massa rhoncus ullamcorper sed vitae nisl. Pellentesque euismod lectus iaculis lacus hendrerit, vel interdum mi suscipit. Sed consequat libero nec tristique malesuada. Donec et vestibulum leo. Proin sit amet diam id sem semper molestie sit amet sit amet nisi. Donec dictum pulvinar mauris, id facilisis lorem tincidunt facilisis. Phasellus ac accumsan nibh. Ut consequat quam eu neque congue scelerisque. Maecenas sit amet est ex. Fusce luctus risus rutrum posuere fermentum. Ut congue lorem arcu, ac fermentum turpis blandit quis. Curabitur arcu diam, malesuada eu accumsan vel, malesuada ut risus. " +
        "Nunc pretium maximus purus, id mattis metus sagittis at. In sem enim, varius eget tincidunt ut, interdum eu felis. Proin in sem ac leo malesuada finibus vel quis nibh. Curabitur a vehicula lorem. Donec turpis libero, scelerisque vitae nibh vitae, auctor rutrum nisl. Phasellus sodales massa ante, in luctus lectus iaculis at. Donec ex velit, cursus at sollicitudin sed, gravida ac quam. Phasellus sed enim ultrices, consectetur ante sit amet, tempus neque. Cras ultricies nec ligula ac varius. In vestibulum ut orci eu convallis. " +
        "Cras est risus, dictum pellentesque est sit amet, blandit tincidunt ipsum. Aenean gravida ligula ut ligula feugiat feugiat. Pellentesque venenatis massa non eros tempor egestas. Morbi eget lorem laoreet, varius orci vel, ornare mi. Aliquam vel velit et nulla suscipit elementum. Duis semper metus sem, eu maximus lectus condimentum ac. Fusce finibus at elit non fermentum. Etiam volutpat consequat dui, ut laoreet nibh scelerisque eu. Etiam luctus tellus augue, at varius urna rhoncus eget. Suspendisse molestie sit amet nulla non pulvinar. Pellentesque eget luctus diam. Fusce id velit porttitor odio porttitor sollicitudin. Quisque eu accumsan justo. Curabitur suscipit accumsan nulla eu gravida. Morbi ut massa tincidunt justo ultrices malesuada. " +
        "Nunc at dui eget ligula dictum ullamcorper nec sit amet mauris. Maecenas auctor sit amet odio varius lacinia. Aenean rhoncus erat sit amet nunc elementum iaculis. Fusce nec blandit nunc, vel vestibulum est. Duis tempus consectetur ultrices. Phasellus ac risus ullamcorper lectus dignissim rutrum in eget risus. Vivamus eget ante est. Mauris ullamcorper eros in facilisis fringilla. Nam metus libero, ullamcorper id viverra vitae, tincidunt sed lorem. In hac habitasse platea dictumst. Mauris gravida ante magna, sit amet finibus ex fermentum lacinia. Nullam nec purus vel enim feugiat feugiat quis ac felis. Suspendisse sapien eros, pellentesque ac ipsum in, venenatis scelerisque odio. Sed eget urna tortor. Mauris velit mauris, euismod sed dolor aliquet, congue feugiat risus. " +
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum at urna pellentesque lorem vestibulum pulvinar. Nam ut malesuada justo, id luctus nisi. Nullam nunc erat, aliquam et faucibus sed, consequat quis lectus. Aenean id libero sit amet ipsum vulputate venenatis. Praesent a ornare nulla, vitae ultrices velit. Nam ut leo id sem rutrum auctor sagittis in ligula. Sed velit enim, ornare vel faucibus ac, posuere sed justo. " +
        "Sed non malesuada lectus, ut scelerisque turpis. Proin ut lorem neque. Phasellus tellus eros, bibendum sed ligula ac, imperdiet vulputate risus. Donec facilisis neque eu egestas interdum. Donec convallis elementum dolor, ac scelerisque nulla mattis vel. Vivamus at commodo nisl. Nam in laoreet libero. Aliquam luctus volutpat enim, sit amet maximus nisl lacinia et. Phasellus et porta est. Suspendisse pellentesque ex tincidunt mauris cursus, at sollicitudin nisi tincidunt. Nam imperdiet mi orci, non porttitor mi congue nec. Maecenas sit amet consectetur dolor, in suscipit odio. Ut pretium ultrices finibus. Donec molestie gravida sem, sit amet suscipit augue porttitor non. Duis condimentum elementum nulla, in lacinia est condimentum sit amet. Donec lectus sapien, finibus ac arcu eu, maximus fermentum nunc. " +
        "Sed rhoncus, justo ac imperdiet hendrerit, mi mauris volutpat neque, tempus congue nisi eros sit amet nisi. Donec vulputate interdum elementum. Vestibulum facilisis odio eu nibh iaculis faucibus. Integer ultrices ipsum facilisis purus lobortis, non consectetur urna sagittis. Duis dapibus sodales varius. Maecenas hendrerit volutpat lorem nec mollis. Nulla tempor sit amet orci et pulvinar. Sed scelerisque viverra magna, eget facilisis risus maximus ac. Donec venenatis ex lacus, sed mollis lectus lacinia eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. " +
        "Praesent orci ligula, blandit in posuere a, ultrices vel nisl. Etiam nec orci varius, maximus erat nec, viverra magna. Nullam massa lacus, dictum id velit eu, pharetra semper lacus. Aliquam ac enim elit. Nam sit amet venenatis mauris. Sed quis lacus non eros facilisis varius at vel neque. Pellentesque commodo sagittis velit rhoncus iaculis. Nullam pharetra justo mauris, at faucibus quam blandit at. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse tristique sollicitudin erat tincidunt fringilla. Quisque ornare mattis turpis, non scelerisque mauris. Nullam eu rhoncus orci, eu consequat erat. Donec ante purus, ultricies nec sagittis in, semper faucibus mauris. " +
        "Mauris a lacus tellus. Duis vitae lacus hendrerit, iaculis purus quis, pretium felis. Suspendisse scelerisque nulla sed volutpat egestas. In hendrerit, tortor ac viverra imperdiet, dui sapien sagittis tortor, ac auctor mi nibh at lorem. Aliquam erat volutpat. Donec rutrum iaculis urna, eu convallis metus faucibus quis. Vivamus iaculis a quam sit amet mattis. Sed blandit justo sit amet est cursus, sit amet bibendum eros pellentesque. Praesent mollis neque dui, eget tristique justo vestibulum ac. Vivamus nibh elit, mollis quis feugiat at, tempor in lorem. Praesent laoreet nisl vitae ante bibendum pellentesque. Donec risus mauris, efficitur ac felis vel, porttitor auctor massa. Praesent convallis risus quis ante vestibulum tristique. Quisque auctor nulla et venenatis mollis. Nam eget sapien sit amet nibh pretium dictum. " +
        "Donec congue tellus tortor, at porttitor augue fermentum nec. Nunc tempor euismod diam non cursus. Maecenas ut euismod est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu ultricies libero, ac porta orci. Etiam bibendum, risus non lacinia euismod, metus mauris vulputate quam, vehicula fringilla massa dui ut justo. Phasellus lacinia sodales odio, a varius purus faucibus sed. Etiam in leo felis. Nunc vestibulum eros velit, vel molestie dui aliquet et. Nunc quis gravida neque, et eleifend elit. Integer in nulla ut metus pulvinar hendrerit. Pellentesque facilisis id dolor quis venenatis. Sed fermentum ultrices felis a rutrum. " +
        "Nullam ornare gravida volutpat. Nulla facilisi. Mauris tempus ex lacus, id sodales erat suscipit sit amet. Vivamus at placerat justo, non iaculis ipsum. Integer at libero est. Sed tincidunt dui quam, at porta magna feugiat sed. Ut ornare, lorem vel dictum sodales, magna metus consequat libero, ut scelerisque arcu odio eleifend felis. Morbi tincidunt blandit nisi, vel mattis magna suscipit at. Nullam metus est, auctor vitae eros vitae, ultricies mattis massa. In in sem at nibh viverra suscipit. Vivamus ac rhoncus ipsum, quis venenatis arcu. Duis suscipit ut ipsum non feugiat. Sed ac volutpat ipsum. Proin a porta ipsum, eu pharetra nisl. In elementum, dolor at luctus condimentum, ex eros feugiat turpis, ac sodales mi arcu et justo. Cras quis felis vel sem sollicitudin congue. " +
        "Nunc eu mauris ac mi rhoncus posuere tristique eget ante. Nam eros tortor, venenatis in interdum non, sollicitudin non sem. Phasellus suscipit maximus ex nec gravida. Duis bibendum vulputate egestas. Proin viverra arcu augue, quis mattis tellus euismod eget. Aliquam erat volutpat. Nulla efficitur velit justo, et rutrum neque finibus ac. Vestibulum egestas tempor tristique. In et convallis arcu, ac aliquam odio. Aliquam aliquam felis vitae neque euismod feugiat. Nullam dapibus egestas ipsum, at rhoncus turpis congue quis. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse sapien lacus, egestas in blandit eu, laoreet vitae arcu. Aliquam erat volutpat. Donec sed nisl convallis justo blandit pretium. " +
        "Sed id quam quis nibh venenatis aliquet sit amet sed enim. Vestibulum vestibulum sem eu ullamcorper pulvinar. Integer pellentesque consequat lacus. Morbi sit amet tincidunt odio. Proin nec pharetra lorem, a maximus leo. Duis at justo nec odio gravida rutrum. Etiam vitae sapien eu nisl viverra ultricies quis sed leo. Mauris fringilla condimentum arcu, vel euismod ligula maximus quis. Pellentesque eget magna vitae urna ultrices cursus. Vestibulum sollicitudin augue dui, eu pellentesque magna vestibulum vel. Morbi congue ultrices leo, in sollicitudin dolor. Duis sit amet dui luctus, mattis arcu ullamcorper, suscipit ante. Ut ac consectetur nisi. Nam faucibus vestibulum purus eu rhoncus. Nulla facilisi. Nullam lacus nunc, sodales ac egestas in, malesuada in arcu. " +
        "Curabitur consectetur orci arcu, ut ultrices leo convallis scelerisque. Nunc bibendum, arcu in mollis aliquet, libero leo volutpat risus, hendrerit viverra enim nibh non sem. Curabitur placerat enim ex, a porta felis scelerisque et. Quisque non purus tempor, malesuada est vitae, pretium ex. Quisque nibh nulla, ultrices quis velit non, sollicitudin malesuada velit. Nullam tincidunt consectetur ex lacinia consectetur. Aenean nec lectus eu mauris viverra fringilla. Phasellus facilisis hendrerit porttitor. Morbi vitae laoreet magna. Aliquam condimentum nulla quis nisi elementum pharetra. Aenean vel condimentum libero. Vestibulum eget quam eu velit sollicitudin efficitur at vitae magna. Vivamus auctor tincidunt blandit. Pellentesque id molestie diam, sed consequat libero. Suspendisse nec commodo ante. Integer vitae enim dictum, vulputate neque ac, placerat odio. " +
        "Donec gravida ut leo semper pulvinar. Donec a erat orci. Fusce sed libero ac massa tincidunt congue at eu augue. Sed nec hendrerit enim, vel pharetra ex. Vestibulum quis lacus accumsan, consequat ipsum egestas, lobortis sem. Sed tincidunt egestas semper. Aenean ut ex venenatis, iaculis augue et, lacinia est. Sed vitae libero maximus, laoreet turpis non, efficitur sem. In hac habitasse platea dictumst. Sed porttitor nisl eget vehicula bibendum. Suspendisse est lectus, viverra id lectus sit amet, ultrices luctus sapien. " +
        "Fusce id vestibulum ante. In accumsan nisi erat, convallis tempor massa eleifend quis. Vivamus quis pretium elit. Sed viverra nibh erat, quis malesuada nisi hendrerit in. In vulputate elit quis eros tincidunt feugiat. Nam eleifend posuere ipsum sit amet pretium. Nullam ultrices neque ac elit fermentum ultrices. Suspendisse eleifend tellus quis ligula faucibus rhoncus. Maecenas dolor massa, interdum non fermentum non, volutpat nec neque. Etiam pellentesque nisl nunc, eu vestibulum risus maximus a. Curabitur facilisis ut quam in cursus. " +
        "Morbi in laoreet turpis. Nam bibendum sapien sit amet porta pretium. Fusce commodo egestas ligula, quis pharetra ipsum venenatis vitae. Aenean accumsan lectus ac nibh tempor varius. Aliquam et turpis felis. Praesent ante sem, lobortis ullamcorper mollis eu, malesuada vel est. Mauris enim est, efficitur a tortor sit amet, finibus maximus libero. Duis vel leo lectus. Phasellus ac magna lectus. Praesent vel quam ipsum. Pellentesque viverra quam eu diam consequat, eu varius turpis efficitur. Nulla luctus neque ac odio rutrum ultrices. Quisque euismod tellus nec neque vestibulum, ac aliquet neque interdum. " +
        "Ut accumsan congue augue eu ultricies. Nullam id sodales erat. Etiam vel fermentum lorem. Curabitur varius quam in dolor tempus fermentum. Integer eget tempus tortor. Morbi elit augue, feugiat nec pharetra sed, congue vel lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque porttitor commodo justo vitae tincidunt. ";
    
        return text.substring(0, ipsumLength);
    }

    render() {
        return (
            <div className={this.props.className} style={this.props.style}>
                <p>{ this.getIpsumText(50) }</p>
            </div>
        );
    }
}

export default LorenIpsum;